### ISSUE TITLE
Tests: keep the html folder and the viewer open

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidmresults-spmhtml#10]
Hi @TomMaullin: could we keep the viewer open and the generated html file (or folder) after running the tests? 

I still get the following error when the viewer is closed:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Channel is already closed.
    at com.teamdev.jxbrowser.chromium.internal.ipc.SocketChannelWriter.write(Unknown Source)
    at com.teamdev.jxbrowser.chromium.internal.ipc.SocketChannel.send(Unknown Source)
    at com.teamdev.jxbrowser.chromium.internal.WebView.a(Unknown Source)
    at com.teamdev.jxbrowser.chromium.internal.WebView.loadURL(Unknown Source)
    at com.teamdev.jxbrowser.chromium.internal.WebView.loadURL(Unknown Source)
    at com.mathworks.html.jxbrowser.chromium.JxBrowserChromiumNavigator$1.run(JxBrowserChromiumNavigator.java:119)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

And I think it is quite useful to have the possibility to inspect the html file after running the tests. What do you think?

**Comment by cmaumet** [comment]
This was partially included in #9. @TomMaullin: could you also remove the lines that delete the `index.html` file in `nidmExampleDataTest`?

**Comment by cmaumet** [comment]
@TomMaullin: am I right in considering that this has been fixed? If so, can you close this issue?

**Comment by TomMaullin** [comment]
Yes, I believe so
